# Generated by Django 6.0.3 on 2026-03-23 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('secteur', models.CharField(choices=[('immobilier', 'Immobilier'), ('agriculture', 'Agriculture'), ('tech', 'Tech / Startup'), ('energie', 'Énergie / Solaire')], max_length=20)),
                ('localisation', models.CharField(max_length=100)),
                ('montant_cible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours de financement'), ('ferme', 'Fermé')], default='ouvert', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('porteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
                ('investisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to='projects.project')),
            ],
            options={
                'unique_together': {('investisseur', 'projet')},
            },
        ),
    ]
