# Generated by Django 6.0.3 on 2026-03-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country_of_residence',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc/documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='investment_areas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='investment_experience',
            field=models.CharField(blank=True, choices=[('debutant', 'Débutant (0-2 ans)'), ('intermediaire', 'Intermédiaire (2-5 ans)'), ('expert', 'Expert (5+ ans)')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='investment_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='investment_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='investor_type',
            field=models.CharField(blank=True, choices=[('individual', 'Investisseur individuel'), ('family_office', 'Family Office'), ('institutionnel', 'Institutionnel'), ('business_angel', 'Business Angel'), ('autre', 'Autre')], max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='motivation',
            field=models.TextField(blank=True, help_text='Pourquoi souhaitez-vous investir en Afrique ?'),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='net_worth',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='proof_of_address',
            field=models.FileField(blank=True, null=True, upload_to='kyc/address/'),
        ),
    ]
